### PR TITLE
Add Tabs to Postmatic Admin Screen

### PR DESCRIPTION
**Pull request by ronalfy**
Adding tabs and background history to Replyable.

### CODE REVIEW

**Comment by cyberhobo** [comment]
Thanks for PRs @ronaldhuereca! Be aware that the TravisCI config for Replyable deploys pushes to master to the WordPress repo. That and some other useful info is in https://github.com/postmatic/postmatic-basic/blob/master/CONTRIBUTING.md.

I'll see if I can make PRs merge to a dev branch by default.

**Comment by ronalfy** [comment]
@cyberhobo gotcha. I can change the branch for the PR I think.

**Comment by cyberhobo** [comment]
Good deal. I think I've got the repo settings so the right thing happens by default now. Cheers!

**Comment by Vernal** [comment]
Thank you guys! Mystery solved!

**Comment by cyberhobo** [comment]
Well I can't find any record of a Travis build that did those deployments. Mysterious, but let's proceed normally and I'll keep an eye out.

**Comment by cyberhobo** [comment]
@Vernal You can merge this when you're happy with it.

**Comment by ronalfy** [comment]
@Vernal you can safely merge this into the develop branch with no changes to master being made.

**Pull request merged**
